### PR TITLE
Gridicons nametag

### PR DESCRIPTION
**Pull request by mapk**
Added the svg-min icon and pushed this branch up again. I believe it just needs to be merged now.

### CODE REVIEW

**Comment by drw158** [comment]
Looks good but not sure what will happen since the other files are already in master. I'll defer to @folletto !

**Comment by folletto** [comment]
Yeah it would have been easier to take master and add the missing bits. :D 
I did a rebase, and I'm merging just to make sure doesn't break anything as I'm not 100% sure what I did was correct. :D

**Comment by mapk** [comment]
Okay, let me know if I can do anything different to make this easier.

**Comment by folletto** [comment]
It's good, rebase done :)

I've also tweaked a bit the source SVG so it's more readable. :)

**Pull request merged**
