### PR TITLE
Add Zoom In and Zoom Out icons

### PR DESCRIPTION
**Pull request by jancavan**
This is a redo of https://github.com/Automattic/gridicons/pull/264. That branch had to be reverted because of some SVG to PDF Kit issues mentioned in: https://github.com/Automattic/gridicons/pull/264#issuecomment-350881014.

This branch adds Zoom in and Zoom out icons:
screen shot 2017-12-07 at 12 27 54 pm

### CODE REVIEW

**Comment by jancavan** [comment]
@folletto In https://github.com/Automattic/gridicons/pull/268/commits/5cfbed321b3f35e503532c99a4b6d7902227d51f, I followed the formatting in the example given in: https://github.com/Automattic/gridicons/blob/b5d36227e554502e78c403c27e6779fc46c470fd/sources/svg/gridicons-create.svg?short_path=34ad600.

**Comment by folletto** [comment]
Looks good! Build, squash and merge 👍

**Comment by jancavan** [comment]
It looks like only the PDFs for the new icons have been generated, so it looks like we're good to go:

```
pdf/gridicons-zoom-in.pdf
pdf/gridicons-zoom-out.pdf
svg-min/gridicons-zoom-in.svg
svg-min/gridicons-zoom-out.svg
```

**Comment by folletto** [comment]
Yes! Lookin' good! 👍

**Pull request merged**
