### PR TITLE
Bug icon

### LINKED ISSUE #175: New icon: bug
screen shot 2016-06-08 at 5 00 09 pm

### PR DESCRIPTION
**Pull request by drw158**
fixes #175 

screen shot 2017-06-15 at 3 19 55 pm
screen shot 2017-06-15 at 3 19 31 pm

### CODE REVIEW

**Comment by folletto** [comment]
It's a nifty little bug :D 

🚢

**Comment by drw158** [comment]
Ok! Ran grunt and everything seems to look good.

**Comment by drw158** [comment]
Removed <g>

**Comment by folletto** [comment]
Let's open the cage for this bug! 🚢

**Comment by drw158** [comment]
🐛

**Pull request merged**
