### PR TITLE
New icon: Product downloadable

### PR DESCRIPTION
**Pull request by jameskoster**
product downloadable

### CODE REVIEW

**Comment by folletto** [comment]
Can we use our standard arrow shape?

i.e. 

screen shot 2016-05-26 at 14 25 43

**Comment by jameskoster** [comment]
Heh, I grabbed this arrow from https://cloudup.com/cYKtx6YCYjt

But yeah, that one would probably look better. Will update.

**Comment by folletto** [comment]
Now that you point it out... that's odd too :D

**Comment by jameskoster** [comment]
Looks better 👍 

download

**Comment by drw158** [comment]
Nice, this idea works well.

**Comment by drw158** [comment]
Updated 

screen shot 2016-05-31 at 4 26 53 pm

**Comment by jameskoster** [comment]
The other product icons have a 2 pixel gap between the edge of the box and the icon within. We could do the same with this if we shrunk the 'shaft' of the arrow by 2 px. Worth it?

**Comment by drw158** [comment]
When viewed at 100% I feel it's more optically balanced than if it had a 2px gap.

screen shot 2016-06-01 at 11 48 38 am

Imo, the arrow on the left feels like it's too far down, the right arrow feels centered and even.

**Comment by folletto** [comment]
I agree. The right, longer one looks better balanced.

**Pull request closed without merging**
