### PR TITLE
Refactoring: simplified design/build process, SVG as master

### PR DESCRIPTION
**Pull request by folletto**
screen shot 2017-06-09 at 18 16 56

This PR is a proposals discussed with @drw158, @jasmussen, and @mattmiklic to simplify the process to add and update Gridicons.

Changes:

1. The master files are SVGs inside `/sources/svg/`
2. **No more AI files** — except for the template
3. **No more Illustrator scripts**
4. Since I was there, I also reviewed the comments in the `Gruntfile.js` to make it more readable.
5. Should also address the question raised in #206: instead of removing `svg/` we remove the AI files, the end result is more tight source SVGs.

Note that it seems a huge PR but most of the 180+ files are just files moved around.

### Benefits

* Faster turnaround of PRs as icons can be more easily merged
* Easier for anyone to add new icons
* Less binary files to handle
* Complete automation is possible

The only slight "con" is that SVGs might lose some editing capabilities the IA have, but since we started Gridicons in 2014 this issue never appeared in practice, and if anything we have used SVG as design sources.

### Historical Note

Initially we wanted to generate everything from Illustrator using Artboards, but we hit Illustrator limit to 100 Artboards (yes, really) and we reverted to single stack in #23. 
We also tried to use Sketch to preserve the ability to see all the icons side by side, but we had issue with that too, see #19 (mostly due to Sketch being not too evolved in SVG export at the time, today might be different).

Android also moved to use SVGs directly (with Android Studio) and iOS still requires a manual conversion to PDF, none of which again requires an Illustrator file. Due to these updated processes, the need for the special `gridicons-32.ai` file is reduced as tweaks should be done on a per-icon basis (see #14), and even there, we can just make `32` versions of the SVG files.

Thus, as long as the template is present to make sure the margins are followed (was added by Dave in #24), our real "master" copy of the icons are the SVG. 

### To test

1. Delete all temp folders: `node_modules`, `build` (even better: a clean git repository)
2. Readme: follow the "Propose a New Icon" steps (without creating a PR)
3. Readme: follow the "Add a Proposed Icon to Gridicons (Admins Only)" steps (without merging any PR)
4. Verify that all the necessary files are re-built as before (`svg-min`, `build`, `php`, `svg-sprite`, `docs`)
5. Try to remove the added icon (from both `sources/svg` and `svg-min`) and check in the diff that everything is restored to the initial state.

### CODE REVIEW

**Comment by drw158** [comment]
I only got tripped up trying to find the `svg` folder. I just pushed an update to the readme to make that more clear.

Here is what was generated with `grunt`

screen shot 2017-06-09 at 3 35 05 pm

Removing the icon from svg and svg-min and grunting, cleanly reverted back to the initial state.

I don't think anything gets generated in `react`? I don't see anything in that folder that needs to be updated. Not sure.

**Comment by drw158** [comment]
Also, we refer to the gridicons-32 file in the readme. Do we still need it? Were the icons in there any different than the 24px icons? I think they were slightly tweaked for mobile.

**Comment by folletto** [comment]
> I only got tripped up trying to find the `svg` folder. I just pushed an update to the readme to make that more clear.

Thank you, I missed that.

> Everything looked good.
> Removing the icon from svg and svg-min and then grunting, cleanly reverted back to the initial state.

Yey! :D 

> I don't think anything gets generated in `react`? I don't see anything in that folder that needs to be updated. Not sure. We might need to update the readme to reflect the new stuff that gets generated.

Good point. I'll look into that.

> Also, we refer to the gridicons-32 file in the readme. Do we still need it? Were the icons in there any different than the 24px icons? I think they were slightly tweaked for mobile.

They were slightly tweaked for sharpness, as mentioned I'm not sure if we need them anymore, but for good measure, I added them back as SVGs in `sources/svg-32`.

Double checked them for sharpness:

screen shot 2017-06-10 at 21 56 46

**Comment by folletto** [comment]
> I don't think anything gets generated in `react`? I don't see anything in that folder that needs to be updated. Not sure. We might need to update the readme to reflect the new stuff that gets generated.

Yes. The script has been modified. `react` contains a source template, the output is in `build`. Was changed in #188. For the scope of this PR I won't change it, I'll do a separate one to clear that up too. I need some extra clarity on the build / publish to npm to do that too. I'll follow up later.

For the time being, I updated the `README.md` file with these details.

**Comment by folletto** [comment]
For clarity, I moved the React templates from `react` to `sources/react`. I checked regenerating the `build` and verified all the files with `md5` and they all match 1:1.

As a reference, currently the npm `package.json` uses only:

```
...
  "files": [
    "build/index.js",
    "build/example.js"
  ],
...
```

**Comment by folletto** [comment]
Ok, all the feedback should be now addressed:

1. React folders clarified ✅ 
2. Gridicons for 32px added as SVG sources ✅ 
3. Output and notes clarified in the readme ✅  

Ready for another review. 👀

**Comment by drw158** [comment]
Everything seems to work. Here are the files that get generated with grunt (excluding the initial svg)

screen shot 2017-06-12 at 9 49 37 am

**Comment by mattmiklic** [comment]
> They were slightly tweaked for sharpness, as mentioned I'm not sure if we need them anymore, but for good measure, I added them back as SVGs in sources/svg-32.

Yeah, the iOS navbar requires 32px icons, and when we tried scaling up from the originals, they weren't quite sharp enough. We probably don't really need the `gridicons-32.ai` file, since it's only those five icons that need the size adjustments, and if we ever end up changing one of the navbar icons it, too, would be a one-time adjustment.

**Comment by folletto** [comment]
Ok, so I think preserving for now the SVG version is good for now. :)

Double thanks @drw158 and @mattmiklic! 💯 

Merging the beast so we can start enjoying the benefits. :)

**Pull request merged**
