### PR TITLE
Fix: Remove <title> tags from SVGs

### PR DESCRIPTION
**Pull request by mladenplavsic**
As described in #205 <title> tags are removed in these usages of SVG:

- svg-min/*.svg
- php/gridicons.php
- svg-sprite/gridicons.svg

This is done by updating ```Gruntfile.js``` - removed "addtitle" task.

Some more things done:

- Updated ```grunt-svgstore``` to version ```1.0.0``` in ```package.json```
- Added option ```includeTitleElement``` and set to ```false``` https://github.com/fweinb/grunt-svgstore#optionsincludetitleelement-since-050
- Removed unnecessary option ```prefix```
- Using ```svg-min/*.svg``` instead of ```svg/*.svg``` for "svgstore" task

### CODE REVIEW

**Comment by folletto** [comment]
`includeTitleElement = false`? Clever. :)

I'm a bit uncomfortable with `fileContent.indexOf( '>' )` which seems too generic, but as we use GIT/PRs if there are odd results should be visible. For reference, I already raised the point in the past, so it's just to make sure we're aware, and there's an issue to fix it: #123. 

---

To test, I checked:

1. No more `title` in svg-min/*.svg ✅ 
2. No more `title` in php/gridicons.php ✅ 
3. No more `title` in svg-sprite/gridicons.svg ✅ 
4. Run `grunt`, no differences expected ✅ 

_Note:_ I had to run `npm install` before running `grunt` for this to work properly.

**Comment by folletto** [comment]
@bluefuton can you drop a quick eye here on the code to have a more expert review? Should be quick :)

**Comment by drw158** [comment]
My PR #208 caused the conflicts. Looks like this collapses the sprite into one line. Note that I added a new icon in the PR.

**Comment by bluefuton** [comment]
Thanks @mladenplavsic! Code looks good to me - just needs rebasing and SVGs regenerating I think 👍

**Comment by drw158** [comment]
@mladenplavsic feel free to squash and merge.

**Comment by mladenplavsic** [comment]
@drw158 I would like to, but I don't have permission for it :-)

**Comment by bluefuton** [comment]
I'll do the honours. Thanks @mladenplavsic!

**Pull request merged**
