### PR TITLE
New icon: play

### LINKED ISSUE #229: New Icon: Play
At the moment we have a Pause icon on the library but it looks we don't have the counter part to do play. 

Can we have a Play icon?

My use case scenario is on the mobile apps we have support for videos on the editor. By default they start paused and it will be nice to overlay a Play icon on top to indicate to the users that it's a video and you can play them.

Here is an example of the current icon we have that is code generated:

screen shot 2017-06-20 at 12 36 50

### PR DESCRIPTION
**Pull request by drw158**
screen shot 2017-06-20 at 2 50 20 pm
screen shot 2017-06-20 at 2 50 07 pm

fixes #229

### CODE REVIEW

**Comment by folletto** [comment]
For reference, this is pause:

screen shot 2017-06-20 at 21 54 00

---

I think it works well. 👍

**Comment by folletto** [comment]
Aside: should we start doing code-review of the SVG during review given the new process?

**Comment by drw158** [comment]
Probably. So:

- add svg to sources folder 
- run grunt
- publish PR mark for review

?

**Comment by folletto** [comment]
I'm slightly for still running grunt just before merge and not for the PR (so it's super simple to contribute for anyone without a grunt setup) — apart from that, yes. 

We just check the SVG source code too during the review basically. Nothing else changes.

**Comment by drw158** [comment]
Removed <g>, should be good to go now 👍

**Comment by folletto** [comment]
Checked 🔍  
Looks good 👀  
Ship it 🚢

**Comment by SergioEstevao** [comment]
Anyone solving the conflict and merging this soon? :)

**Comment by drw158** [comment]
Yes

**Comment by drw158** [comment]
I messed up the rebase. Changes from other PRs are showing up in this one. Should I make a new fresh branch?

**Comment by SergioEstevao** [comment]
It will be better to keep it clean from non-related changes.

**Comment by drw158** [comment]
I wasn't able to get this PR in working order. I just created a new branch.

**Pull request closed without merging**
