### PR TITLE
New icon: Credit card verification

### PR DESCRIPTION
**Pull request by jameskoster**
ccv

### CODE REVIEW

**Comment by folletto** [comment]
I feel there are a lot of different line weight in here, also the corner cut out in that way is a little too thin on smaller sizes. Can we normalize weights and simplify the shape?

**Comment by jameskoster** [comment]
Yeah I guess the cut-out isn't necessary. How do you feel about this;

ccv)

**Comment by folletto** [comment]
Definitely better.

A clarification: "verification" here means "to check the verification number" or "card has been verified"? I'm asking because if it's the second then a ✓ might work better in terms of symbology.

**Comment by jameskoster** [comment]
It's an icon we use to illustrate the location of a cards security code (last 3 digits of number on the back).

**Comment by folletto** [comment]
Ok it's perfect then. :)

**Comment by drw158** [comment]
Nice, at first I liked the idea of using the checkmark with the credit card icon. I would consider just using the card icon with the code shown, like this:

screen shot 2016-05-26 at 10 28 57 am

Or maybe just delete the left portion of the number on your icon, like so:

screen shot 2016-05-26 at 10 32 17 am

Either way, I think the latest iteration on your icon works.

**Comment by jameskoster** [comment]
I think having the left portion is helpful as it's quite common for the last 3 digits of a longer number to be requested. This helps demonstrate that.

I'll double check that we definitely still need this icon. Might be one we can skip.

**Comment by jameskoster** [comment]
Just confirmed, this is only used on the frontend. We'll create a separate dedicated svg but it doesn't need to go in gridicons.

**Pull request closed without merging**
