### PR TITLE
New icon: Order refunded

### PR DESCRIPTION
**Pull request by jameskoster**
outline
solid

### CODE REVIEW

**Comment by folletto** [comment]
We might want to give the same "spacing" as mentioned in #159, like `+`:

screen shot 2016-05-26 at 13 34 55

Even if here might be harder given the shape of the arrow. Maybe instead of a "U" turn could be just a "L"?

**Comment by jameskoster** [comment]
refund
refund

**Comment by jameskoster** [comment]
Hmm, I'm not sure this is such a great metaphor for a refund actually.

Maybe the arrow should be pointing backwards?

**Comment by folletto** [comment]
I agree. The latest one is good in terms of alignment with our patterns, but meaning is a little less evident.

What about arrow down pointing a coin?

**Comment by drw158** [comment]
I think I would prefer just to use our `undo` icon for this instead, unless we are also using `undo` elsewhere in the same interface. I think using existing icons is usually better. 

Here are some ideas if we decide to create a new icon:

screen shot 2016-05-26 at 10 19 01 am
screen shot 2016-05-26 at 10 18 29 am

Maybe we relate it to whatever we do for the price icon? #47

**Comment by folletto** [comment]
> Maybe we relate it to whatever we do for the price icon?

Great idea. That + arrow turning back (first icon above) could work well :)

**Comment by drw158** [comment]
Idea for refund now that we have a price icon:

screen shot 2016-06-06 at 11 20 53 am
screen shot 2016-06-06 at 11 20 38 am

I still think we could just use the `undo` icon for refund.

**Comment by folletto** [comment]
Have you tried also the bill inside the circular arrow?

This looks ok, but I'd reverse the direction of the arrow. ;)

**Comment by drw158** [comment]
Yep makes more sense with the arrow reversed :)

screen shot 2016-06-06 at 11 29 13 am

I can't seem to put the price icon within an arrow circle and stick to our standards:

screen shot 2016-06-06 at 11 38 46 am

But I had the idea of using the rotate icon (circle face used because of space concerns):

screen shot 2016-06-06 at 11 46 13 am

screen shot 2016-06-06 at 11 46 21 am

**Comment by folletto** [comment]
Agreed, the circle is a bit difficult with our standards.

The arrow up is good, and I agree the last one is the best one. That's the closest one to the meaning we want to express. 👍

**Comment by drw158** [comment]
Ok, thanks Davide, I will proceed with this one.

> The arrow up is good, and I agree the last one is the best one. That's the closest one to the meaning we want to express. 👍

**Pull request closed without merging**
