### PR TITLE
New icon: Shipping

### PR DESCRIPTION
**Pull request by jameskoster**
shipping

Based on the cart icon

### CODE REVIEW

**Comment by folletto** [comment]
I think this needs some work, feels very odd. :)

Some random inspiration from a quick scan on google images:

screen shot 2016-05-26 at 14 44 29


screen shot 2016-05-26 at 14 44 38

**Comment by kellychoffman** [comment]
Noun project has some [good trucks](https://thenounproject.com/search/?q=shipping%20truck) for inspiration. 

A box truck type would be appropriate for shipping I think. Something like the one below, but facing forward?

screen shot 2016-05-26 at 8 04 33 am

**Comment by drw158** [comment]
Yes, I think a truck would be great for this. Your icon isn't quite there yet. Here is the work I've done for a truck (I'm not satisfied with it yet)

screen shot 2016-05-26 at 9 51 57 am

Material Design has a nice one:

screen shot 2016-05-26 at 9 52 43 am

**Comment by folletto** [comment]
Your second one seems a good direction to me 👍

**Comment by jameskoster** [comment]
> Your second one seems a good direction to me

I like that one too.

**Comment by drw158** [comment]
Here is my new truck icon:

screen shot 2016-06-01 at 4 25 58 pm
screen shot 2016-06-01 at 4 25 35 pm

thoughts?

**Comment by jameskoster** [comment]
I like it. Any reason you ditched the cut-out on the container?

**Comment by folletto** [comment]
The shape is nice. I was wondering about the cut-out too, mostly because feels a bit too heavy. Here's a quick mock:

screen shot 2016-06-02 at 10 51 15

I guess a concern are the lower part with the wheels, where the line weight is more than our patterns standard. However it gives the van a more "van-like" look as well (the bottom part darker) so I'm not sure if we're beyond the limits here or not. :)

**Comment by jameskoster** [comment]
I prefer that one personally.

**Comment by drw158** [comment]
Thanks @folletto, I much prefer your icon. Updated PR:

screen shot 2016-06-02 at 10 32 34 am
screen shot 2016-06-02 at 10 32 19 am

**Pull request closed without merging**
