### PR TITLE
New updates to help icons

### PR DESCRIPTION
**Pull request by drw158**
## Before/After

screen shot 2016-05-19 at 3 42 01 pm
screen shot 2016-05-19 at 3 41 32 pm

### CODE REVIEW

**Comment by drw158** [comment]
fixes #144

**Comment by melchoyce** [comment]
New one is much better.

**Comment by rickybanister** [comment]
the only downside I see to the new icon is that at small size the dot is very close to the rest of the figure. The old one had a little more breathing room, is that fixable?

**Comment by jasmussen** [comment]
What Rick said, otherwise 👍

**Comment by folletto** [comment]
👍

**Comment by drw158** [comment]
Yea, I tried to keep that space 2px, but I couldn't work it out. It would make the ? too tall, and therefore not centered. Also, there wouldn't be room for the outlined version.

screen shot 2016-05-20 at 10 15 54 am

I was encouraged though, that the Material help icons have a 1px space on the outlined version as well:

screen shot 2016-05-20 at 10 13 31 am

**Comment by jasmussen** [comment]
The original is nice enough to merge, I think, so all's good on that front. However I can't help but ask: do we actually need an outline version?

**Comment by folletto** [comment]
>  However I can't help but ask: do we actually need an outline version?

If we have a rationale, I think it's fine...

...

...do we have a clear way to tell when to use one or the other? :D

**Comment by drw158** [comment]
Here's more options 

screen shot 2016-05-20 at 10 45 20 am

**Comment by drw158** [comment]
Outline version is there as an option for designers.

**Comment by drw158** [comment]
I'm gonna go ahead and merge this because of https://github.com/Automattic/gridicons/pull/156#issuecomment-220641017

As always, it can be iterated on in the future.

**Pull request merged**
