### PR TITLE
New icon: Order cancelled

### PR DESCRIPTION
**Pull request by jameskoster**
outline
solid

### CODE REVIEW

**Comment by folletto** [comment]
I would try to keep here the same proportions as the `+` icon, so a smaller `x`:

screen shot 2016-05-26 at 13 34 55

**Comment by jameskoster** [comment]
cancelled
cancelled

**Comment by folletto** [comment]
👍

**Comment by drw158** [comment]
Just style variants, or do they mean 2 different things?

I would think about using the `block` icon instead. Maybe it depends on the interface these will be used in. Either way, these are pretty generic, so I'm not opposed. I'm worried these might be used for "close". That might be ok though.

**Comment by folletto** [comment]
>  I'm worried these might be used for "close". That might be ok though.

Good point actually.

Do you think we should have an icon for "order"?

**Comment by jameskoster** [comment]
> I'm worried these might be used for "close". That might be ok though.

I thought that'd be a benefit? It's true that might be a more frequent use-case though so perhaps we should use that for the name?

Not sure if I should open a separate issue for this, but I was originally planning to use `checkmark-circle` for completed orders. But there's not an 'outline' counterpart. Worth creating a separate icon for completed orders?

> Do you think we should have an icon for "order"?

Would probably be useful.

**Comment by drw158** [comment]
> I thought that'd be a benefit? It's true that might be a more frequent use-case though so perhaps we should use that for the name?

I don't imagine the overlap in usage being a big problem; the designer of the interface will just need to make sure they don't use them together

> Not sure if I should open a separate issue for this, but I was originally planning to use checkmark-circle for completed orders.

We aren't using that icon for the Reader anymore, so maybe it'd be worth spending some time on.

Imo, this might be the best way to go about it:

- don't worry about making outline versions (not necessary)
- don't make an `order` icon

screen shot 2016-05-26 at 11 20 15 am
screen shot 2016-05-26 at 11 22 29 am


order complete, canceled, paused, and processing.

**Comment by folletto** [comment]
The first 4 looks like a good combo to me. :)

**Comment by drw158** [comment]
Or, outlined version: 

screen shot 2016-05-26 at 11 27 22 am

**Comment by jameskoster** [comment]
> The first 4 looks like a good combo to me. :)

I agree. I think we should be consistent and make them all have the containing circle.

Speaking of consistent, should we update `checkmark-circle` so that the check mark isn't 'breaking out' of the circle?

**Comment by drw158** [comment]
Here's the discussion on the check mark circle https://github.com/Automattic/gridicons/issues/31#issuecomment-121731004

I do think it has more character with it breaking out. I'm on the fence.

Could do something like this:

screen shot 2016-05-26 at 12 28 18 pm

**Comment by folletto** [comment]
> I do think it has more character with it breaking out.

Agreed. Adds definitely character to it, and you mock nails both styles imho. :)

**Comment by drw158** [comment]
I propose:

- Go with the first row here: https://github.com/Automattic/gridicons/pull/159#issuecomment-221921747
- Don't do the outlined version of these quite yet.
- I would name this icon `gridicons-cross-circle`

screen shot 2016-05-27 at 3 00 06 pm

**Comment by folletto** [comment]
👍  makes sense

**Comment by drw158** [comment]
Updated as outlined above

**Pull request closed without merging**
