### PR TITLE
Add plans icon

### LINKED ISSUE #240: New icon: Jetpack logo (plans)
Unfortunately this is another logo, but we need to add it for the time being.

We use the Jetpack logo for the Plans icon:

screen shot 2017-07-19 at 2 49 23 pm

Much like the W logo for 'My Sites', the Jetpack logo should be added to Gridicons and named 'plans' or 'plan'.

We need to be clear that this logo is only to be used for the Plans icon, because the logo vectors will be tweaked a bit because of the small size. There is a separate component in Calypso for the unaltered logo.

This is necessary, because at the moment, the svg being using for the Plans icon does not fit the Gridicons template, and it appears bigger than other circle icons.

### PR DESCRIPTION
**Pull request by mattmiklic**
Fixes #240, #261. Props to @MichaelArestad for the 24px hinted version of the Jetpack logo.

screen shot 2018-01-10 at 2 21 33 pm

screen shot 2018-01-10 at 2 21 16 pm

### CODE REVIEW

**Comment by folletto** [comment]
Looks good. 👍

**Comment by folletto** [comment]
Build added. Ready to merge.

**Comment by elibud** [comment]
@frosty once this is merged can you regenerate the Gridicons for iOS? Also, do you know who takes care of that in Android? Thank you

**Comment by rickybanister** [comment]
Thanks!

**Comment by MichaelArestad** [comment]
LGTM!

**Pull request merged**
