### PR TITLE
New icon: Product grouped

### PR DESCRIPTION
**Pull request by jameskoster**
product grouped

### CODE REVIEW

**Comment by folletto** [comment]
Nice.

I'd probably cut straight the bottom line of the box behind, instead of trying to contour the other box outline.

**Comment by jameskoster** [comment]
good call, updated.

**Comment by drw158** [comment]
Updated 

screen shot 2016-05-31 at 5 14 45 pm

**Comment by jameskoster** [comment]
We may not be using this icon now so this can be put on ice. Not sure if it's worth creating a label to that effect?

**Pull request closed without merging**
