### PR TITLE
New icon: Order on hold

### PR DESCRIPTION
**Pull request by jameskoster**
outline
solid

### CODE REVIEW

**Comment by folletto** [comment]
Looks good. 👍

**Comment by kellychoffman** [comment]
👍  Nice.

**Comment by drw158** [comment]
Cool, looks good. Are these 2 icons just style variants, or do they mean 2 different things?

**Comment by jameskoster** [comment]
Just style variants.

**Comment by drw158** [comment]
Same as here: https://github.com/Automattic/gridicons/pull/159#issuecomment-222240203

I wouldn't do the outlined version for right now.

`gridicons-order-paused` or maybe more generic, `gridicons-pause`. Could be used in a video player or slideshow.

**Comment by jameskoster** [comment]
+1 for `pause`.

**Comment by drw158** [comment]
Updated with new name and removed outlined icon.

**Pull request closed without merging**
