### PR TITLE
Add "trending" icon for post sorting in Discover

### PR DESCRIPTION
**Pull request by Gio2018**
Adds the "trending" icon (see image below)

<p align=center>

</p>

### CODE REVIEW

**Comment by davewhitley** [comment]
This icon needs a little bit of fixing with the grid

Screen Shot 2021-02-22 at 3 25 11 PM

**Comment by Gio2018** [comment]
Thank you for the quick feedback @davewhitley !! I'm working with @mbshakti to address this issue.

**Comment by Gio2018** [comment]
Hey @davewhitley I have updated the icon, please let me know if it looks good now.

**Review by davewhitley — CHANGES_REQUESTED** [review]
I went ahead and made some tweaks. Here ya go!

SVG https://cloudup.com/coKvpbiotPX

Before/After
Screen Shot 2021-02-23 at 10 36 05 AM

**Comment by Gio2018** [comment]
Just replaced this one too, thank you!!

**Review by davewhitley — COMMENTED** [review]
Looks good, now you just need to run the build process 👍

**Review by davewhitley — APPROVED** [review]

**Pull request merged**
