### PR TITLE
New icon: Filter

### PR DESCRIPTION
**Pull request by jameskoster**
filter

Another one required for the synchrotron project.

### CODE REVIEW

**Comment by folletto** [comment]
Sorry I'm a bit on mobile so I can't do it myself right now... maybe can you post it at the default size in context with the other icons to evaluate it?

In isolation, seems ok. :)

**Comment by jameskoster** [comment]
Ah yea, sorry about that. Here it is with a few other icons;

filter

**Comment by folletto** [comment]
Looks good to me. Maybe the funnel bottom/end pipe can be a tiny smaller, but it's just an experiment, maybe it gets too narrow on small sizes. 👍  for me.

**Comment by drw158** [comment]
The rounded corners are a little wonky; not sure what happened there:

screen shot 2016-06-16 at 11 01 22 am

**Comment by drw158** [comment]
Ok, I updated the icon with some fixes:

- fixed rounded corners
- deleted unnecessary points
- made the spout 1 pt shorter
- centered the icon in the canvas

Only thing I'm worried about is the icon might be a little small in the canvas 

screen shot 2016-06-16 at 11 07 38 am
screen shot 2016-06-16 at 11 06 25 am

**Comment by drw158** [comment]
Yes, I think @foletto will be able to help you if you get stuck

**Comment by folletto** [comment]
Check the "Add a Proposed Icon to Gridicons (Admins Only)" part in the readme for full details. On doubt, just ask. :)

**Comment by jameskoster** [comment]
Done!

**Comment by drw158** [comment]
Looks like this could be merged after conflicts resolved

**Comment by jameskoster** [comment]
Had some issues resolving the conflicts (pesky .ai files) so I opened a new PR; https://github.com/Automattic/gridicons/pull/185

**Pull request closed without merging**
