### PR TITLE
Adds the "recent" icon for post sorting in Discover

### PR DESCRIPTION
**Pull request by Gio2018**
Adds the "recent" icon (see image below)

<p align=center>

</p>

### CODE REVIEW

**Comment by davewhitley** [comment]
I think it might be best to use an existing open source icon for this one. The one in the PR has some alignment issues with the grid.

Here's a new one from [Material Design Icons](https://materialdesignicons.com/). It follows our guidelines and is properly aligned:

image
alert-decagram-outline 1

SVG https://cloudup.com/caURluhTRte

**Comment by Gio2018** [comment]
Hey @davewhitley , thanks for reviewing!! Just replaced the recent icon with the one you provided, please let me know if I did it right. Thank you

**Review by davewhitley — COMMENTED** [review]
Looks good, now you just need to run the build process 👍

**Comment by Gio2018** [comment]
Done!! thanks so much for the support @davewhitley !! Since this is the first time I do this, if you could give a final look to this PR and #314 before merging, it would be great!!

**Pull request merged**
