### PR TITLE
New icon: next page

### PR DESCRIPTION
**Pull request by drw158**
closes #201 

screen shot 2017-05-24 at 12 15 28 pm
screen shot 2017-05-24 at 12 15 03 pm
screen shot 2017-05-24 at 12 14 54 pm

screen shot 2017-05-24 at 12 19 25 pm

### CODE REVIEW

**Comment by folletto** [comment]
Design is good, SVG is good. 👍 


GitHug is saying there are conflicts tho, which is odd.

**Comment by drw158** [comment]
Hm, looks like there is a grunt task that injects the svg sprite in the index.html files.

This commit deletes the svg sprite and adds a function, but probably did not remove the grunt task:

https://github.com/Automattic/gridicons/commit/73ef60aa31499f806055ca600fc3c13df018a4f7

@keoshi it looks like your function here generates the svg sprite:

https://github.com/Automattic/gridicons/blob/73ef60aa31499f806055ca600fc3c13df018a4f7/svg-sprite/index.html#L86

but you may have forgotten to remove the grunt task that also generates it. Does that sound right?

**Comment by keoshi** [comment]
@drw158 That's the [SVG for Everybody](https://github.com/jonathantneal/svg4everybody) function that uses a polyfill when supporting older browsers, not a grunt task. Not sure what the problem is, but I'm happy to help if you give me more details.

**Comment by folletto** [comment]
I also just noticed, title in the SVG is `1Artboard 1`.

**Comment by drw158** [comment]
Thanks @keoshi, it was might fault. I was working off of an old master!

**Comment by folletto** [comment]
All good, 🚢

**Comment by drw158** [comment]
thanks!

**Pull request merged**
