### PR TITLE
New icon: Product

### PR DESCRIPTION
**Pull request by jameskoster**
product

### CODE REVIEW

**Comment by folletto** [comment]
👍  in line with the others. :)

**Comment by kellychoffman** [comment]
👍  Looks good. We can use the for 'package' too instead of: https://github.com/Automattic/gridicons/issues/151

**Comment by drw158** [comment]
Also not two dimensional. Here are some ideas:

screen shot 2016-05-26 at 10 02 22 am

screen shot 2016-05-26 at 10 05 09 am

**Comment by folletto** [comment]
...it's 2d if you imagine it being a box with a lid partially open :P 

But I get the point, yes. To me this is a doable (and contained) exception, but I'd prefer too to go fully 2d as expected.

The pure square is too generic to be used here imho, and we need to consider all the other usages.

@jameskoster can you post a screenshot here with all the icons so far that use the "box" shape?

**Comment by folletto** [comment]
Also cross referencing all the related issues: #163, #164, #165, #166, #167, #169.

**Comment by jameskoster** [comment]
Current box icons;

boxes

**Comment by folletto** [comment]
Ok some brainstorming:

screen shot 2016-05-26 at 16 30 03

**Comment by jameskoster** [comment]
I think the first is the only feasible one seeing as we need to put something 'inside' the box to demonstrate the type of product? There's probably not enough room to do that with the other concepts.

**Comment by drw158** [comment]
Here's a bunch of ideas going off of @folletto. Sorry it's messy.

screen shot 2016-05-26 at 12 16 31 pm

**Comment by jameskoster** [comment]
How about this @drw158 @folletto ?

products

It gives an exact square for the main box area which is nice for putting things inside. Needs some tidying but you get the idea.

**Comment by folletto** [comment]
That idea seems working well to me! :)

**Comment by jameskoster** [comment]
Tidied up a bit;

icons

**Comment by drw158** [comment]
I think you are headed in the right direction. I think we could give a bit more personality to the regular package. The proportions of a perfect square don't sit quite well to me, and your icons might seem slightly larger compared to the other icons in Gridicons. Here is my take:

screen shot 2016-05-27 at 10 03 12 am
screen shot 2016-05-27 at 10 05 30 am

We should simplify the multiple package icon; I think it should be similar to the multiple images one. It's hard to make it not look awkward in such a small space:

screen shot 2016-05-27 at 10 07 50 am
screen shot 2016-05-27 at 10 07 38 am

**Comment by folletto** [comment]
That looks great :)

**Comment by jameskoster** [comment]
Yup that looks like a winner! Would you mind updating the relevant PR's @drw158 ?

**Comment by drw158** [comment]
Updated product icon

screen shot 2016-05-31 at 3 54 27 pm

**Comment by kellychoffman** [comment]
👍  Love it.

**Pull request closed without merging**
