### PR TITLE
New icon: Bolt

### PR DESCRIPTION
**Pull request by joanrho**
Here's a proposed lightning bolt for Issue #155 
bolt

In context with a few other Gridicons: 
bolt-in-context

### CODE REVIEW

**Comment by mapk** [comment]
I did a quick review of how the angles are lining up with the other icons and it looks good! The weight of the icon feels great too.

icon-angles

**Comment by joanrho** [comment]
Thanks @mapk!

Just added a resize icon, too:
resize

In context with other Gridicons:
resize-in-context

**Comment by MichaelArestad** [comment]
This looks pretty dang good so far. It seems like a good candidate for the Upgrades icon, but probably not the power icon. The power icons generally tend to be pointy on both ends. Here's what we're currently using:

image

I also checked your icon at 1x. It looks pretty good, but might be a touch sharper if you can somehow align the points to whole pixels. (maybe not)

image

The resize looks pretty perfect, but I would remove it from this PR and add it in a second so we can discuss and merge one at a time.

**Comment by joanrho** [comment]
Thanks for the feedback, @MichaelArestad! Good catch—the upper left "zig" corner and inner left and right "zag" corners seem to be slightly off whole pixels. Will update that!

bolt-grids

**Comment by drw158** [comment]
A bolt icon was added in #183 after this PR was opened. 

We should keep this PR open, but know that it will replace the current bolt icon:

**Comment by drw158** [comment]
will be handled in #187

**Pull request closed without merging**
