### PR TITLE
Update icon: create

### PR DESCRIPTION
**Pull request by folletto**
screen shot 2017-10-16 at 13 55 40

screen shot 2017-10-16 at 13 58 01

This icon proposal builds on the long discussion on #242. 
As stated there this change will improve under these aspects:

1. To make the icon more understandable, as the pencil/paper abstract one didn't perform too well and plus seems a better choice to "add content"
2. To make the icon more generic so it would suggest not just text but also images.
3. Being an incremental change on the previous one.
4. Still being different from the other "plus" icons we have.

Downside:

1. It de-emphasise the "text" component of creating new content

As the discussion happened already extensively in #242 for 2+ months, the feedback at this stage is on the technical aspects of it:

* SVG cleanliness
* Does it work in Sketch / Illustrator
* Does it conform to the Gridicons standards

If yes, thumb up and we'll merge. ;)

### CODE REVIEW

**Comment by jasmussen** [comment]
Visually I love this one. 👍 👍

I had some npm woes with this one, not sure why — probably issues on my end:

screen shot 2017-10-23 at 12 58 00

**Comment by folletto** [comment]
Odd, the SVG source got mangled in the build process:

```
<svg viewBox="0 0 2<g><g>4 24" xmlns="http://www.w3.org/2000/svg"><path d="M21 14v5c0 1.105-.895 2-2 2H5c-1.105 0-2-.895-2-2V5c0-1.105.895-2 2-2h5v2H5v14h14v-5h2z"/><path d="M21 7h-4V3h-2v4h-4v2h4v4h2V9h4"/></g></g></svg>
```

Note the `<g><g>` in the middle. I feel something's broken with the `<g>` insertion. Looking into that.

**Comment by jasmussen** [comment]
I think I've seen this. Try and outline/flatten the icon in question. I think that has to happen regardless, because the React component can only handle a single path inside the file (which is a problem probably worth addressing separately).

**Comment by folletto** [comment]
Ah possibly, I was trying to keep the plus separate. I'll check that too.

**Comment by folletto** [comment]
Found: `svg-transform-add-g` specifically checks `viewBox` at the END of the SVG. Looking at ways to refactor it.

**Comment by folletto** [comment]
Ok, the new build task in #259 should fix it. :)

**Comment by drw158** [comment]
Looks good! 👍

**Comment by folletto** [comment]
Wonderful. This should automatically land in Calypso the next time we update Gridicons. 

If we want this to happen sooner, we can push it. :D

**Pull request merged**
