### PR TITLE
New icon: Order processing

### PR DESCRIPTION
**Pull request by jameskoster**
outline
solid

### CODE REVIEW

**Comment by folletto** [comment]
We might want to give the same "spacing" as mentioned in #159, like `+`:

screen shot 2016-05-26 at 13 34 55

**Comment by jameskoster** [comment]
I think the only way we'd be able to do that would be to have the dots not fit the grid. Otherwise I think they're too small?

processing

**Comment by folletto** [comment]
screen shot 2016-05-26 at 15 31 21

Yeah, the dots might be a bit bigger, to be optically of the same size of the lines. :)

**Comment by drw158** [comment]
I like the idea. I would try using 1.5px dots — that is a trick that we can use when we run into these situations.

**Comment by jameskoster** [comment]
The one on the left has 1.5px dots.

processing

**Comment by drw158** [comment]
I think this will work.

**Comment by drw158** [comment]
Maybe `gridicons-more-circle` would be more generic and appropriate

**Comment by drw158** [comment]
Removed outlined icon and renamed main icon to `gridicons-ellipsis-circle`

**Pull request closed without merging**
