### PR TITLE
New icon: Product external

### PR DESCRIPTION
**Pull request by jameskoster**
external product

### CODE REVIEW

**Comment by folletto** [comment]
This is so good! :)

👍

**Comment by drw158** [comment]
Nice. What does product external mean? That the products lives on another website?

**Comment by jameskoster** [comment]
Yup. IE you list the product on your site but when the visitor goes to purchase they're redirected to amazon or wherever.

**Comment by drw158** [comment]
Updated

screen shot 2016-05-31 at 4 51 41 pm

**Comment by jameskoster** [comment]
Awesome!

**Pull request closed without merging**
